spring:
  application:
    name: book-api

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG

content-folder: /book-api/src/main/resources/file-storage/book-contents/
cover-folder: /book-api/src/main/resources/file-storage/book-covers/